version: "3"
services:
  bot:
    build: .
    restart: always
    environment:
      DISCORD_TOKEN:
      SHORTER_URL:
      CONFIG_PATH: /config
    volumes:
      - "config:/config"
volumes:
  config:
